#define MASQUERADE_MAX_LEVEL 25

#define MASQUERADE_REASON_PREFERENCES "Preferences"
#define MASQUERADE_REASON_NPC "NPC"
#define MASQUERADE_REASON_OBJECT "Object"
#define MASQUERADE_REASON_OTHER "Other"
